name: "Unit tests / Cover"

on:
  pull_request:
    branches:
      - master


jobs:

  run-unittests:
    name: unit-${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        allow-prereleases: true

    - name: Install nox
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox

    - name: Run unit tests
      run: |
        tox -e py${{ matrix.python }}

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-artifacts
        path: .coverage.py${{ matrix.python }}

  report-coverage:
    name: cover
    runs-on: ubuntu-latest
    needs:
        - run-unittests

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install coverage
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install coverage

    - name: Download coverage results
      uses: actions/download-artifact@v2
      with:
        name: coverage-artifacts
        path: .coverage-results/

    - name: Report coverage results
      run: |
        coverage combine .coverage-results/.coverage*
        coverage report --show-missing --fail-under=100
