name: "Unit tests / Cover"

on:
  pull_request:
    branches:
      - master


jobs:

  run-unittests:
    name: unit-${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.9"
            toxenv: py39
          - python: "3.10"
            toxenv: py310
          - python: "3.11"
            toxenv: py311
          - python: "3.12"
            toxenv: py312
          - python: "3.13"
            toxenv: py313
          - python: "3.14"
            toxenv: py314
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        allow-prereleases: true

    - name: Install tox
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox

    - name: Run unit tests
      run: |
        tox -e ${{ matrix.toxenv }}

  report-coverage:
    name: cover
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - run: pip install tox
    - run: tox -e py39,py314,cover
