name: "Unit tests / Cover"

on:
  pull_request:
    branches:
      - master


jobs:

  run-unittests:
    name: unit-${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "2.7"
            toxenv: "py27"
          - python: "3.5"
            toxenv: "py35"
          - python: "3.6"
            toxenv: "py36"
          - python: "3.7"
            toxenv: "py37"
          - python: "3.8"
            toxenv: "py38"

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install tox
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox

    - name: Run unit tests
      env:
        COVERAGE_FILE: .coverage-${{matrix.python }}
      run: |
        tox -e ${{ matrix.toxenv }}

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-artifacts
        path: .coverage.${{ matrix.toxenv }}

  report-coverage:
    name: cover
    runs-on: ubuntu-latest
    needs:
        - run-unittests

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install coverage
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install coverage

    - name: Download coverage results
      uses: actions/download-artifact@v2
      with:
        name: coverage-artifacts
        path: .coverage-results/

    - name: Report coverage results
      run: |
        coverage combine .coverage-results/.coverage*
        coverage report --show-missing --fail-under=100
